language: node_js
node_js:
   - "6.6.0"
services:
   - mongodb
install:
  - npm install
script:
  - npm run lint && npm run analyze-coverage
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
