language: node_js
node_js:
   - "4.4.0"
install:
  - npm install
script:
  - npm run lint && npm run analyze-coverage
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
